Updated for Qdrant VDB
superlinked/VectorHub pull request #118
Opened 2024-01-12 12:29 UTC by atarora

Updated for Qdrant VDB

2024-01-12 13:02 UTC, dhruv-anand-aintech commented on docs/tools/vdb_table/data/qdrant.json
> +    "source_url": "https://colab.research.google.com/github/qdrant/examples/blob/master/rag-openai-qdrant/rag-openai-qdrant.ipynb",
This column is for "Calls LLM internally for RAG". Every VDB would be able to call OpenAI as in the notebook you have shared.

2024-01-12 13:02 UTC, dhruv-anand-aintech commented on docs/tools/vdb_table/data/qdrant.json
> +    "support": "full",
this should be 'partial' as it is only in a specific case

2024-01-12 13:03 UTC, dhruv-anand-aintech requested changes
Please address the comments

2024-01-12 15:44 UTC, atarora commented
> Please address the comments

Done

2024-01-15 07:24 UTC, dhruv-anand-aintech approved these changes

2024-01-15 07:25 UTC, merged

2024-01-15 07:25 UTC, dhruv-anand-aintech commented
Thanks for keeping the table up-to-date, @atarora!